language: node_js
node_js:
  - '0.8'
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-vemn-stack' ]; then cd .. && eval "mv $currentfolder generator-vemn-stack" && cd generator-vemn-stack; fi

